version: '3'

services:
  api:
    image: strapi/strapi
    environment:
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
    ports:
      - 1337:1337
    volumes:
      - ./strapi-api:/usr/src/api/strapi-api
      - /usr/src/api/strapi-api/node_modules
    depends_on:
      - db
    restart: always

  db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=strapi
    ports:
      - 27017
    restart: always
